export interface WordPair {
  correct: string
  incorrect: string
}

export const WORD_PAIRS: WordPair[] = [
  // Original (i correct)
  { correct: 'kick', incorrect: 'keck' },
  { correct: 'lick', incorrect: 'leck' },
  { correct: 'pick', incorrect: 'peck' },
  { correct: 'stick', incorrect: 'steck' },
  { correct: 'thick', incorrect: 'theck' },
  { correct: 'click', incorrect: 'cleck' },
  { correct: 'trick', incorrect: 'treck' },
  { correct: 'brick', incorrect: 'breck' },
  { correct: 'quick', incorrect: 'queck' },
  { correct: 'chick', incorrect: 'check' },
  { correct: 'sick', incorrect: 'seck' },
  { correct: 'wick', incorrect: 'weck' },
  { correct: 'slick', incorrect: 'sleck' },
  { correct: 'flick', incorrect: 'fleck' },
  { correct: 'prick', incorrect: 'preck' },

  // Additional with i correct (one syllable)
  { correct: 'bit', incorrect: 'bet' },
  { correct: 'sit', incorrect: 'set' },
  { correct: 'pit', incorrect: 'pet' },
  { correct: 'wit', incorrect: 'wet' },
  { correct: 'lit', incorrect: 'let' },
  { correct: 'git', incorrect: 'get' },
  { correct: 'din', incorrect: 'den' },
  { correct: 'pin', incorrect: 'pen' },
  { correct: 'tin', incorrect: 'ten' },
  { correct: 'lid', incorrect: 'led' },
  { correct: 'rid', incorrect: 'red' },
  { correct: 'rip', incorrect: 'rep' },
  { correct: 'miss', incorrect: 'mess' },
  { correct: 'list', incorrect: 'lest' },
  { correct: 'fill', incorrect: 'fell' },
  { correct: 'hill', incorrect: 'hell' },
  { correct: 'will', incorrect: 'well' },
  { correct: 'bill', incorrect: 'bell' },

  // Additional with i correct (two syllables)
  { correct: 'bitter', incorrect: 'better' },
  { correct: 'litter', incorrect: 'letter' },
  { correct: 'sitter', incorrect: 'setter' },
  { correct: 'bidding', incorrect: 'bedding' },
  { correct: 'missing', incorrect: 'messing' },
  { correct: 'ridden', incorrect: 'redden' },
  { correct: 'finder', incorrect: 'fender' },
  { correct: 'tinder', incorrect: 'tender' },
  { correct: 'filter', incorrect: 'felter' },

  // With e correct (one syllable)
  { correct: 'bed', incorrect: 'bid' },
  { correct: 'sell', incorrect: 'sill' },
  { correct: 'tell', incorrect: 'till' },
  { correct: 'dwell', incorrect: 'dwill' },
  { correct: 'spell', incorrect: 'spill' },
  { correct: 'swell', incorrect: 'swill' },
  { correct: 'bent', incorrect: 'bint' },
  { correct: 'dent', incorrect: 'dint' },
  { correct: 'lent', incorrect: 'lint' },
  { correct: 'sent', incorrect: 'sint' },
  { correct: 'tent', incorrect: 'tint' },
  { correct: 'went', incorrect: 'wint' },
  { correct: 'best', incorrect: 'bist' },
  { correct: 'jest', incorrect: 'jist' },
  { correct: 'nest', incorrect: 'nist' },
  { correct: 'pest', incorrect: 'pist' },
  { correct: 'test', incorrect: 'tist' },
  { correct: 'vest', incorrect: 'vist' },
  { correct: 'west', incorrect: 'wist' },
  { correct: 'zest', incorrect: 'zist' },
  { correct: 'bend', incorrect: 'bind' },
  { correct: 'fend', incorrect: 'find' },
  { correct: 'lend', incorrect: 'lind' },
  { correct: 'mend', incorrect: 'mind' },
  { correct: 'rend', incorrect: 'rind' },
  { correct: 'send', incorrect: 'sind' },
  { correct: 'tend', incorrect: 'tind' },
  { correct: 'wend', incorrect: 'wind' },

  // With e correct (two syllables)
  { correct: 'wetter', incorrect: 'witter' },
  { correct: 'wedding', incorrect: 'widding' },
  { correct: 'mender', incorrect: 'minder' },
  { correct: 'bender', incorrect: 'binder' },
  { correct: 'sender', incorrect: 'sinder' },
  { correct: 'render', incorrect: 'rinder' },
  { correct: 'gender', incorrect: 'ginder' },
  { correct: 'petal', incorrect: 'pital' },
  { correct: 'metal', incorrect: 'mital' },
  { correct: 'dental', incorrect: 'dintal' },
  { correct: 'mental', incorrect: 'mintal' },
  { correct: 'rental', incorrect: 'rintal' },
]
